Profile.create(
  first_name:        "Kyle",
  last_name:         "Reierson",
  city:  			 "Denver",
  state: 			 "Colorado",
  country: 			 "USA",
  trading_style: 	 "Value investing",
  fav_sector: 		 "Technology",
)



Company.create(id: 1,   symbol: "ANF",  name: "Abercrombie & Fitch", 		sector: "Consumer Discretionary")
Company.create(id: 2,   symbol: "AMZN", name: "Amazon.com Inc.",			sector: "Consumer Discretionary")
Company.create(id: 3,   symbol: "AZO",  name: "AutoZone Inc.",				sector: "Consumer Discretionary")
Company.create(id: 4,   symbol: "BBY",  name: "Best Buy Co. Inc.",			sector: "Consumer Discretionary")
Company.create(id: 5,   symbol: "CCL",  name: "Carnival Corp.",				sector: "Consumer Discretionary")
Company.create(id: 6,   symbol: "CBS",  name: "CBS Corp.",					sector: "Consumer Discretionary")
Company.create(id: 7,   symbol: "CMG",  name: "Chipotle Mexican Grill",		sector: "Consumer Discretionary")
Company.create(id: 8,   symbol: "CMCSA", name: "Comcast Corp.",				sector: "Consumer Discretionary")
Company.create(id: 9,   symbol: "DTV",  name: "DirecTV",					sector: "Consumer Discretionary")
Company.create(id: 10,  symbol: "DLTR", name: "Dollar Tree", 				sector: "Consumer Discretionary")
Company.create(id: 11,  symbol: "EXPE", name: "Expedia Inc.", 				sector: "Consumer Discretionary")
Company.create(id: 12,  symbol: "F",    name: "Ford Motor", 				sector: "Consumer Discretionary")
Company.create(id: 13,  symbol: "GPS",  name: "(The) Gap", 					sector: "Consumer Discretionary")
Company.create(id: 14,  symbol: "GT",   name: "Goodyear Tire & Rubber", 	sector: "Consumer Discretionary")
Company.create(id: 15,  symbol: "HOG",  name: "Harley-Davidson", 			sector: "Consumer Discretionary")
Company.create(id: 16,  symbol: "HAS",  name: "Hasbro Inc.", 				sector: "Consumer Discretionary")
Company.create(id: 17,  symbol: "HD",   name: "Home Depot", 				sector: "Consumer Discretionary")
Company.create(id: 18,  symbol: "LOW",  name: "Lowe's Cos.", 				sector: "Consumer Discretionary")
Company.create(id: 19,  symbol: "M",    name: "Macy's Inc.", 				sector: "Consumer Discretionary")
Company.create(id: 20,  symbol: "MAR",  name: "Marriott Int'l.", 			sector: "Consumer Discretionary")
Company.create(id: 21,  symbol: "MCD",  name: "McDonald's Corp.", 			sector: "Consumer Discretionary")
Company.create(id: 22,  symbol: "MHP",  name: "McGraw-Hill", 				sector: "Consumer Discretionary")
Company.create(id: 23,  symbol: "NKE",  name: "NIKE Inc.", 					sector: "Consumer Discretionary")
Company.create(id: 24,  symbol: "JWN",  name: "Nordstrom", 					sector: "Consumer Discretionary")
Company.create(id: 25,  symbol: "ORLY", name: "O'Reilly Automotive", 		sector: "Consumer Discretionary")
Company.create(id: 26,  symbol: "RL",   name: "Polo Ralph Lauren Corp.",    sector: "Consumer Discretionary")
Company.create(id: 27,  symbol: "SHLD", name: "Sears Holdings Corp.", 		sector: "Consumer Discretionary")
Company.create(id: 28,  symbol: "SHW",  name: "Sherwin-Williams", 			sector: "Consumer Discretionary")
Company.create(id: 29,  symbol: "SPLS", name: "Staples Inc.", 				sector: "Consumer Discretionary")
Company.create(id: 30,  symbol: "SBUX", name: "Starbucks Corp.", 			sector: "Consumer Discretionary")
Company.create(id: 31,  symbol: "TGT",  name: "Target Corp.", 				sector: "Consumer Discretionary")
Company.create(id: 32,  symbol: "TWX",  name: "Time Warner Inc.", 			sector: "Consumer Discretionary")
Company.create(id: 33,  symbol: "TWC",  name: "Time Warner Cable Inc.",     sector: "Consumer Discretionary")
Company.create(id: 34,  symbol: "URBN", name: "Urban Outfitters", 			sector: "Consumer Discretionary")
Company.create(id: 35,  symbol: "VIAB", name: "Viacom Inc.", 				sector: "Consumer Discretionary")
Company.create(id: 36,  symbol: "DIS",  name: "Walt Disney Co.", 			sector: "Consumer Discretionary")
Company.create(id: 37,  symbol: "WHR",  name: "Whirlpool Corp.", 			sector: "Consumer Discretionary")
Company.create(id: 38,  symbol: "WYNN", name: "Wynn Resorts Ltd.", 			sector: "Consumer Discretionary")
Company.create(id: 39,  symbol: "YUM",  name: "Yum! Brands Inc.", 			sector: "Consumer Discretionary")
Company.create(id: 40,  symbol: "AVP",  name: "Avon Products", 				sector: "Consumer Staples")
Company.create(id: 41,  symbol: "CPB",  name: "Campbell Soup", 				sector: "Consumer Staples")
Company.create(id: 42,  symbol: "KO",   name: "Coca Cola Co.", 				sector: "Consumer Staples")
Company.create(id: 43,  symbol: "CL",   name: "Colgate-Palmolive", 			sector: "Consumer Staples")
Company.create(id: 44,  symbol: "COST", name: "Costco Co.", 				sector: "Consumer Staples")
Company.create(id: 45,  symbol: "CVS",  name: "CVS Caremark Corp.", 		sector: "Consumer Staples")
Company.create(id: 46,  symbol: "DPS",  name: "Dr Pepper Snapple Group",    sector: "Consumer Staples")
Company.create(id: 47,  symbol: "GIS",  name: "General Mills", 				sector: "Consumer Staples")
Company.create(id: 48,  symbol: "HNZ",  name: "Heinz (H.J.)", 				sector: "Consumer Staples")
Company.create(id: 49,  symbol: "HRL",  name: "Hormel Foods Corp.", 		sector: "Consumer Staples")
Company.create(id: 50,  symbol: "K",    name: "Kellogg Co.", 				sector: "Consumer Staples")
Company.create(id: 51,  symbol: "KMB",  name: "Kimberly-Clark", 			sector: "Consumer Staples")
Company.create(id: 52,  symbol: "KFT",  name: "Kraft Foods Inc.", 			sector: "Consumer Staples")
Company.create(id: 53,  symbol: "KR",   name: "Kroger Co.", 				sector: "Consumer Staples")
Company.create(id: 54,  symbol: "TAP",  name: "Molson Coors Brewing Co.", 	sector: "Consumer Staples")
Company.create(id: 55,  symbol: "MNST", name: "Monster Beverage", 			sector: "Consumer Staples")
Company.create(id: 56,  symbol: "PEP",  name: "PepsiCo Inc.", 				sector: "Consumer Staples")
Company.create(id: 57,  symbol: "PM",   name: "Philip Morris Int'l", 		sector:"Consumer Staples")
Company.create(id: 58,  symbol: "PG",   name: "Procter & Gamble", 			sector: "Consumer Staples")
Company.create(id: 59,  symbol: "SWY",  name: "Safeway Inc.", 				sector: "Consumer Staples")
Company.create(id: 60,  symbol: "SJM",  name: "Smucker (J.M.)", 			sector: "Consumer Staples")
Company.create(id: 61,  symbol: "HSY",  name: "The Hershey Company", 		sector: "Consumer Staples")
Company.create(id: 62,  symbol: "TSN",  name: "Tyson Foods", 				sector: "Consumer Staples")
Company.create(id: 63,  symbol: "WMT",  name: "Wal-Mart Stores", 			sector: "Consumer Staples")
Company.create(id: 64,  symbol: "WAG",  name: "Walgreen Co.", 				sector: "Consumer Staples")
Company.create(id: 65,  symbol: "WFM",  name: "Whole Foods Market", 		sector: "Consumer Staples")
Company.create(id: 66,  symbol: "APC",  name: "Anadarko Petroleum Corp", 	sector: "Energy")
Company.create(id: 67,  symbol: "APA",  name: "Apache Corp.", 				sector: "Energy")
Company.create(id: 68,  symbol: "CHK",  name: "Chesapeake Energy", 			sector: "Energy")
Company.create(id: 69,  symbol: "CVX",  name: "Chevron Corp.", 				sector: "Energy")
Company.create(id: 70,  symbol: "COP",  name: "ConocoPhillips", 			sector: "Energy")
Company.create(id: 71,  symbol: "DVN",  name: "Devon Energy Corp.", 		sector: "Energy")
Company.create(id: 72,  symbol: "DO",   name: "Diamond Offshore Drilling",  sector: "Energy")
Company.create(id: 73,  symbol: "XOM",  name: "Exxon Mobil Corp.", 			sector: "Energy")
Company.create(id: 74,  symbol: "HAL",  name: "Halliburton Co.", 			sector: "Energy")
Company.create(id: 75,  symbol: "NBL",  name: "Noble Energy Inc.", 			sector: "Energy")
Company.create(id: 76,  symbol: "OXY",  name: "Occidental Petroleum", 		sector: "Energy")
Company.create(id: 77,  symbol: "BTU",  name: "Peabody Energy", 			sector: "Energy")
Company.create(id: 78,  symbol: "PSX",  name: "Phillips 66", 				sector: "Energy")
Company.create(id: 79,  symbol: "VLO",  name: "Valero Energy", 				sector: "Energy")
Company.create(id: 80,  symbol: "AFL",  name: "AFLAC Inc.", 				sector: "Financials")
Company.create(id: 81,  symbol: "ALL",  name: "Allstate Corp.", 			sector: "Financials")
Company.create(id: 82,  symbol: "AXP",  name: "American Express Co.", 		sector: "Financials")
Company.create(id: 83,  symbol: "AXP",  name: "American Express Co.", 		sector: "Financials")
Company.create(id: 84,  symbol: "AIG",  name: "American Intl Group Inc.", 	sector: "Financials")
Company.create(id: 85,  symbol: "BAC",  name: "Bank of America Corp.", 		sector: "Financials")
Company.create(id: 86,  symbol: "BRK.B", name: "Berkshire Hathaway", 		sector: "Financials")
Company.create(id: 87,  symbol: "COF",  name: "Capital One Financial", 		sector: "Financials")
Company.create(id: 88,  symbol: "SCHW", name: "Charles Schwab", 			sector: "Financials")
Company.create(id: 89,  symbol: "C",    name: "Citigroup Inc.", 			sector: "Financials")
Company.create(id: 90,  symbol: "CMA",  name: "Comerica Inc.", 				sector: "Financials")
Company.create(id: 91,  symbol: "ETFC", name: "E-Trade", 					sector: "Financials")
Company.create(id: 92,  symbol: "GS",   name: "Goldman Sachs Group", 		sector: "Financials")
Company.create(id: 93,  symbol: "JPM",  name: "JPMorgan Chase & Co.", 		sector: "Financials")
Company.create(id: 94,  symbol: "MET",  name: "MetLife Inc.", 				sector: "Financials")
Company.create(id: 95,  symbol: "MS,",   name: "Morgan Stanley", 			sector: "Financials")
Company.create(id: 96,  symbol: "PGR",  name: "Progressive Corp.", 			sector: "Financials")
Company.create(id: 97,  symbol: "PLD",  name: "ProLogis", 					sector: "Financials")
Company.create(id: 98,  symbol: "PRU",  name: "Prudential Financial", 		sector: "Financials")
Company.create(id: 99,  symbol: "PSA",  name: "Public Storage", 			sector: "Financials")
Company.create(id: 100, symbol: "TRV",  name: "The Travelers Companies Inc.", sector: "Financials")
Company.create(id: 101, symbol: "TROW", name: "T. Rowe Price Group", 		sector: "Financials")
Company.create(id: 102, symbol: "WFC",  name: "Wells Fargo", 				sector: "Financials")
Company.create(id: 103, symbol: "WY",   name: "Weyerhaeuser Corp.", 		sector: "Financials")
Company.create(id: 104, symbol: "BMY",  name: "Bristol-Myers Squibb", 		sector: "Health Care")
Company.create(id: 105, symbol: "DVA",  name: "DaVita Inc.", 				sector: "Health Care")
Company.create(id: 106, symbol: "JNJ",  name: "Johnson & Johnson", 			sector: "Health Care")
Company.create(id: 107, symbol: "MRK",  name: "Merck & Co.", 				sector: "Health Care")
Company.create(id: 108, symbol: "PFE",  name: "Pfizer Inc.", 				sector: "Health Care")
Company.create(id: 109, symbol: "UNH",  name: "United Health Group Inc.", 	sector: "Health Care")
Company.create(id: 110, symbol: "MMM",  name: "3M Co.", 					sector: "Industrials")
Company.create(id: 111, symbol: "BA",   name: "Boeing Company", 			sector: "Industrials")
Company.create(id: 112, symbol: "CHRW", name: "C. H. Robinson Worldwide", 	sector: "Industrials")
Company.create(id: 113, symbol: "CAT",  name: "Caterpillar Inc.", 			sector: "Industrials")
Company.create(id: 114, symbol: "CTAS", name: "Cintas Corp.", 				sector: "Industrials")
Company.create(id: 115, symbol: "DE",   name: "Deere & Co.", 				sector: "Industrials")
Company.create(id: 116, symbol: "FDX",  name: "FedEx Corp.", 				sector: "Industrials")
Company.create(id: 117, symbol: "GD",   name: "General Dynamics", 			sector: "Industrials")
Company.create(id: 118, symbol: "GE",   name: "General Electric", 			sector: "Industrials")
Company.create(id: 119, symbol: "GWW",  name: "Grainger (W.W.) Inc.", 		sector: "Industrials")
Company.create(id: 120, symbol: "HON",  name: "Honeywell Int'l Inc.", 		sector: "Industrials")
Company.create(id: 121, symbol: "LLL",  name: "L-3 Communications", 		sector: "Industrials")
Company.create(id: 122, symbol: "LMT",  name: "Lockheed Martin Corp.", 		sector: "Industrials")
Company.create(id: 123, symbol: "NOC",  name: "Northrop Grumman Corp.", 	sector: "Industrials")
Company.create(id: 124, symbol: "PBI",  name: "Pitney-Bowes", 				sector: "Industrials")
Company.create(id: 125, symbol: "RTN",  name: "Raytheon Co.", 				sector: "Industrials")
Company.create(id: 126, symbol: "LUV",  name: "Southwest Airlines", 		sector: "Industrials")
Company.create(id: 127, symbol: "TYC",  name: "Tyco International", 		sector: "Industrials")
Company.create(id: 128, symbol: "UNP",  name: "Union Pacific", 				sector: "Industrials")
Company.create(id: 129, symbol: "UPS",  name: "United Parcel Service", 		sector: "Industrials")
Company.create(id: 130, symbol: "UTX",  name: "United Technologies", 		sector: "Industrials")
Company.create(id: 131, symbol: "WM",   name: "Waste Management Inc.", 		sector: "Industrials")
Company.create(id: 132, symbol: "ACN",  name: "Accenture", 					sector: "Information Technology")
Company.create(id: 133, symbol: "ADBE", name: "Adobe Systems Inc.", 		sector: "Information Technology")
Company.create(id: 134, symbol: "AAPL", name: "Apple Inc.", 				sector: "Information Technology")
Company.create(id: 135, symbol: "CSCO", name: "Cisco Systems", 				sector: "Information Technology")
Company.create(id: 136, symbol: "CTXS", name: "Citrix Systems", 			sector: "Information Technology")
Company.create(id: 137, symbol: "DELL", name: "Dell Inc.", 					sector: "Information Technology")
Company.create(id: 138, symbol: "EBAY", name: "eBay Inc.", 					sector: "Information Technology")
Company.create(id: 139, symbol: "FIS",  name: "Fidelity National Information Services", sector: "Information Technology")
Company.create(id: 140, symbol: "GOOG", name: "Google Inc.", 				sector: "Information Technology")
Company.create(id: 141, symbol: "HPQ",  name: "Hewlett-Packard", 			sector: "Information Technology")
Company.create(id: 142, symbol: "INTC", name: "Intel Corp.", 				sector: "Information Technology")
Company.create(id: 143, symbol: "IBM",  name: "Int'l Bus. Machines (IBM)", 	sector: "Information Technology")
Company.create(id: 144, symbol: "INTU", name: "Intuit Inc.", 				sector: "Information Technology")
Company.create(id: 145, symbol: "JNPR", name: "Juniper Networks", 			sector: "Information Technology")
Company.create(id: 146, symbol: "MA",   name: "Mastercard Inc.", 			sector: "Information Technology")
Company.create(id: 147, symbol: "MSFT", name: "Microsoft Corp.", 			sector: "Information Technology")
Company.create(id: 148, symbol: "MSI",  name: "Motorola Solutions Inc.",    sector: "Information Technology")
Company.create(id: 149, symbol: "NTAP", name: "NetApp", 					sector: "Information Technology")
Company.create(id: 150, symbol: "ORCL", name: "Oracle Corp.", 				sector: "Information Technology")
Company.create(id: 151, symbol: "CRM",  name: "Salesforce.com", 			sector: "Information Technology")
Company.create(id: 152, symbol: "SNDK", name: "SanDisk Corp.", 				sector: "Information Technology")
Company.create(id: 153, symbol: "STX",  name: "Seagate Technology", 		sector: "Information Technology")
Company.create(id: 154, symbol: "TXN",  name: "Texas Instruments", 			sector: "Information Technology")
Company.create(id: 155, symbol: "V",    name: "Visa Inc.",					sector: "Information Technology")
Company.create(id: 156, symbol: "WU",   name: "Western Union Co.", 			sector: "Information Technology")
Company.create(id: 157, symbol: "XRX",  name: "Xerox Corp.", 				sector: "Information Technology")
Company.create(id: 158, symbol: "YHOO", name: "Yahoo Inc.", 				sector: "Information Technology")
Company.create(id: 159, symbol: "AA",   name: "Alcoa Inc.", 				sector: "Materials")
Company.create(id: 160, symbol: "BLL",  name: "Ball Corp.", 				sector: "Materials")
Company.create(id: 161, symbol: "DOW",  name: "Dow Chemical", 				sector: "Materials")
Company.create(id: 162, symbol: "DD",   name: "Du Pont (E.I.)", 			sector: "Materials")
Company.create(id: 163, symbol: "ECL",  name: "Ecolab Inc.", 				sector: "Materials")
Company.create(id: 164, symbol: "MON",  name: "Monsanto Co.", 				sector: "Materials")
Company.create(id: 165, symbol: "NEM",  name: "Newmont Mining Corp.", 		sector: "Materials")
Company.create(id: 166, symbol: "NUE",  name: "Nucor Corp.", 				sector: "Materials")
Company.create(id: 167, symbol: "X",    name: "United States Steel Corp.",  sector: "Materials")
Company.create(id: 168, symbol: "T",    name: "AT&T Inc.", 					sector: "Telecommunications Services")
Company.create(id: 169, symbol: "CTL",  name: "CenturyLink Inc.", 			sector: "Telecommunications Services")
Company.create(id: 170, symbol: "S",    name: "Sprint Nextel Corp.", 		sector: "Telecommunications Services")
Company.create(id: 171, symbol: "VZ",   name: "Verizon Communications", 	sector: "Telecommunications Services")
Company.create(id: 172, symbol: "ED",   name: "Consolidated Edison", 		sector: "Utilities")
Company.create(id: 173, symbol: "DUK",  name: "Duke Energy", 				sector: "Utilities")
Company.create(id: 174, symbol: "XEL",  name: "Xcel Energy Inc.", 			sector: "Utilities")