Profile.create(
  first_name:        "Kyle",
  last_name:         "Reierson",
  city:  			 "Denver",
  state: 			 "Colorado",
  country: 			 "USA",
  trading_style: 	 "Value investing",
  fav_sector: 		 "Technology",
)



Company.create(id: 1,   symbol: "ANF",  name: "Abercrombie & Fitch", 		sector: "Consumer Discretionary", industry: "Family Clothing Stores", 									headquarters: "New Albany, Ohio")
Company.create(id: 2,   symbol: "AMZN", name: "Amazon.com Inc.",			sector: "Consumer Discretionary", industry: "Electronic Shopping & Mail-Order Houses", 					headquarters: "Seattle, Washington")
Company.create(id: 3,   symbol: "AZO",  name: "AutoZone Inc.",				sector: "Consumer Discretionary", industry: "Automotive Parts & Accessories Stores", 					headquarters: "Memphis, Tennessee")
Company.create(id: 4,   symbol: "BBY",  name: "Best Buy Co. Inc.",			sector: "Consumer Discretionary", industry: "Appliance, Television, & Other Electronics Stores", 		headquarters: "Richfield, Minnesota")
Company.create(id: 5,   symbol: "CCL",  name: "Carnival Corp.",				sector: "Consumer Discretionary", industry: "Deep Sea, Coastal, & Great Lakes Water Transportation", 	headquarters: "Miami, Florida")
Company.create(id: 6,   symbol: "CBS",  name: "CBS Corp.",					sector: "Consumer Discretionary", industry: "Cable & Other Subscription Programming", 					headquarters: "New York, New York")
Company.create(id: 7,   symbol: "CMG",  name: "Chipotle Mexican Grill",		sector: "Consumer Discretionary", industry: "Restaurants", 												headquarters: "Denver, Colorado")
Company.create(id: 8,   symbol: "CMCSA", name: "Comcast Corp.",				sector: "Consumer Discretionary", industry: "Paper Bag & Coated & Treated Paper Manufacturing", 		headquarters: "St Paul, Minnesota")
Company.create(id: 9,   symbol: "DTV",  name: "DirecTV",					sector: "Consumer Discretionary", industry: "CATV Systems", 											headquarters: "El Segundo, California")
Company.create(id: 10,  symbol: "DLTR", name: "Dollar Tree", 				sector: "Consumer Discretionary", industry: "General Merchandise Stores", 								headquarters: "Chesapeake, Virginia")
Company.create(id: 11,  symbol: "EXPE", name: "Expedia Inc.", 				sector: "Consumer Discretionary", industry: "Lodging", 													headquarters: "Bellevue, Washington")
Company.create(id: 12,  symbol: "F",    name: "Ford Motor", 				sector: "Consumer Discretionary", industry: "Automobile & Light Duty Motor Vehicle Manufacturing", 		headquarters: "Dearborn, Michigan")
Company.create(id: 13,  symbol: "GPS",  name: "(The) Gap", 					sector: "Consumer Discretionary", industry: "Family Clothing Stores", 									headquarters: "San Francisco, California")
Company.create(id: 14,  symbol: "GT",   name: "Goodyear Tire & Rubber", 	sector: "Consumer Discretionary", industry: "Tire Manufacturing", 										headquarters: "Akron, Ohio")
Company.create(id: 15,  symbol: "HOG",  name: "Harley-Davidson", 			sector: "Consumer Discretionary", industry: "Other Transportation Equipment Manufacturing", 			headquarters: "Milwaukee, Wisconsin")
Company.create(id: 16,  symbol: "HAS",  name: "Hasbro Inc.", 				sector: "Consumer Discretionary", industry: "Doll, Toy, & Game Manufacturing", 							headquarters: "Pawtucket, Rhode Island")
Company.create(id: 17,  symbol: "HD",   name: "Home Depot", 				sector: "Consumer Discretionary", industry: "Home Centers", 											headquarters: "Cobb County, Georgia")
Company.create(id: 18,  symbol: "LOW",  name: "Lowe's Cos.", 				sector: "Consumer Discretionary", industry: "Home Centers", 											headquarters: "North Wilkesboro, North Carolina")
Company.create(id: 19,  symbol: "M",    name: "Macy's Inc.", 				sector: "Consumer Discretionary", industry: "Department/Specialty Retail Stores", 						headquarters: "Cincinnati, Ohio")
Company.create(id: 20,  symbol: "MAR",  name: "Marriott Int'l.", 			sector: "Consumer Discretionary", industry: "Hotels (except Casino Hotels) & Motels", 					headquarters: "Bethesda, Maryland")
Company.create(id: 21,  symbol: "MCD",  name: "McDonald's Corp.", 			sector: "Consumer Discretionary", industry: "Limited-Service Eating Places", 							headquarters: "Oak Brook, Illinois")
Company.create(id: 22,  symbol: "MHP",  name: "McGraw-Hill", 				sector: "Consumer Discretionary", industry: "Book Publishers", 											headquarters: "New York, New York")
Company.create(id: 23,  symbol: "NKE",  name: "NIKE Inc.", 					sector: "Consumer Discretionary", industry: "Footwear Manufacturing", 									headquarters: "Washington County, Oregon")
Company.create(id: 24,  symbol: "JWN",  name: "Nordstrom", 					sector: "Consumer Discretionary", industry: "Family Clothing Stores", 									headquarters: "Seattle, Washington")
Company.create(id: 25,  symbol: "ORLY", name: "O'Reilly Automotive", 		sector: "Consumer Discretionary", industry: "Automotive Parts & Accessories Stores", 					headquarters: "Springfield, Missouri")
Company.create(id: 26,  symbol: "RL",   name: "Polo Ralph Lauren Corp.",    sector: "Consumer Discretionary", industry: "Men's & Boys' Cut & Sew Apparel Manufacturing", 			headquarters: "New York, New York")
Company.create(id: 27,  symbol: "SHLD", name: "Sears Holdings Corp.", 		sector: "Consumer Discretionary", industry: "All Other General Merchandise Stores", 					headquarters: "Hoffman Estates, Illinois")
Company.create(id: 28,  symbol: "SHW",  name: "Sherwin-Williams", 			sector: "Consumer Discretionary", industry: "Paint & Coating Manufacturing", 							headquarters: "Cleveland, Ohio")
Company.create(id: 29,  symbol: "SPLS", name: "Staples Inc.", 				sector: "Consumer Discretionary", industry: "Office Supplies & Stationery Stores", 						headquarters: "Framingham, Massachusetts")
Company.create(id: 30,  symbol: "SBUX", name: "Starbucks Corp.", 			sector: "Consumer Discretionary", industry: "Limited-Service Eating Places", 							headquarters: "Seattle, Washington")
Company.create(id: 31,  symbol: "TGT",  name: "Target Corp.", 				sector: "Consumer Discretionary", industry: "All Other General Merchandise Stores", 					headquarters: "Minneapolis, Minnesota")
Company.create(id: 32,  symbol: "TWX",  name: "Time Warner Inc.", 			sector: "Consumer Discretionary", industry: "Motion Picture & Video Production", 						headquarters: "New York, New York")
Company.create(id: 33,  symbol: "TWC",  name: "Time Warner Cable Inc.",     sector: "Consumer Discretionary", industry: "Television Services", 										headquarters: "New York, New York")
Company.create(id: 34,  symbol: "URBN", name: "Urban Outfitters", 			sector: "Consumer Discretionary", industry: "Apparel Stores", 											headquarters: "Philadelphia, Pennsylvania")
Company.create(id: 35,  symbol: "VIAB", name: "Viacom Inc.", 				sector: "Consumer Discretionary", industry: "Broadcasting & Entertainment", 							headquarters: "New York, New York")
Company.create(id: 36,  symbol: "DIS",  name: "Walt Disney Co.", 			sector: "Consumer Discretionary", industry: "Services-Misc. Amusement & Recreation", 					headquarters: "Burbank, California")
Company.create(id: 37,  symbol: "WHR",  name: "Whirlpool Corp.", 			sector: "Consumer Discretionary", industry: "Consumer Electronics/Appliances", 							headquarters: "Benton Harbor, Michigan")
Company.create(id: 38,  symbol: "WYNN", name: "Wynn Resorts Ltd.", 			sector: "Consumer Discretionary", industry: "Resorts & Casinos", 										headquarters: "Las Vegas, Nevada")
Company.create(id: 39,  symbol: "YUM",  name: "Yum! Brands Inc.", 			sector: "Consumer Discretionary", industry: "Restaurants", 												headquarters: "Louisville, Kentucky")
Company.create(id: 40,  symbol: "AVP",  name: "Avon Products", 				sector: "Consumer Staples", 	  industry: "Toilet Preparation Manufacturing", 						headquarters: "New York, New York")
Company.create(id: 41,  symbol: "CPB",  name: "Campbell Soup", 				sector: "Consumer Staples", 	  industry: "Fruit & Vegetable Canning, Pickling, & Drying", 			headquarters: "Camden, New Jersey")
Company.create(id: 42,  symbol: "KO",   name: "Coca Cola Co.", 				sector: "Consumer Staples", 	  industry: "Flavoring Syrup & Concentrate Manufacturing", 				headquarters: "Atlanta, Georgia")
Company.create(id: 43,  symbol: "CL",   name: "Colgate-Palmolive", 			sector: "Consumer Staples", 	  industry: "Toilet Preparation Manufacturing", 						headquarters: "New York, New York")
Company.create(id: 44,  symbol: "COST", name: "Costco Co.", 				sector: "Consumer Staples", 	  industry: "Warehouse Clubs & Supercenters", 							headquarters: "Issaquah, Washington")
Company.create(id: 45,  symbol: "CVS",  name: "CVS Caremark Corp.", 		sector: "Consumer Staples", 	  industry: "Pharmacies & Drug Stores", 								headquarters: "Woonsocket, Rhode Island")
Company.create(id: 46,  symbol: "DPS",  name: "Dr Pepper Snapple Group",    sector: "Consumer Staples", 	  industry: "Beverages (Production/Distribution)", 						headquarters: "Plano, Texas")
Company.create(id: 47,  symbol: "GIS",  name: "General Mills", 				sector: "Consumer Staples", 	  industry: "Breakfast Cereal Manufacturing", 							headquarters: "Golden Valley, Minnesota")
Company.create(id: 48,  symbol: "HNZ",  name: "Heinz (H.J.)", 				sector: "Consumer Staples", 	  industry: "Fruit & Vegetable Canning, Pickling, & Drying", 			headquarters: "Pittsburgh, Pennsylvania")
Company.create(id: 49,  symbol: "HRL",  name: "Hormel Foods Corp.", 		sector: "Consumer Staples", 	  industry: "Animal Slaughtering & Processing", 						headquarters: "Austin, Minnesota")
Company.create(id: 50,  symbol: "K",    name: "Kellogg Co.", 				sector: "Consumer Staples", 	  industry: "Breakfast Cereal Manufacturing", 							headquarters: "Battle Creek, Michigan")
Company.create(id: 51,  symbol: "KMB",  name: "Kimberly-Clark", 			sector: "Consumer Staples", 	  industry: "Paper Mills", 												headquarters: "Irving, Texas")
Company.create(id: 52,  symbol: "KFT",  name: "Kraft Foods Inc.", 			sector: "Consumer Staples", 	  industry: "Packaged Foods", 											headquarters: "Northfield, Illinois")
Company.create(id: 53,  symbol: "KR",   name: "Kroger Co.", 				sector: "Consumer Staples", 	  industry: "Supermarkets & Other Grocery (except Convenience) Stores", headquarters: "Cincinnati, Ohio")
Company.create(id: 54,  symbol: "TAP",  name: "Molson Coors Brewing Co.", 	sector: "Consumer Staples", 	  industry: "Breweries", 												headquarters: "Denver, Colorado")
Company.create(id: 55,  symbol: "MNST", name: "Monster Beverage", 			sector: "Consumer Staples", 	  industry: "Advertising Agencies", 									headquarters: "Corona, California")
Company.create(id: 56,  symbol: "PEP",  name: "PepsiCo Inc.", 				sector: "Consumer Staples", 	  industry: "Flavoring Syrup & Concentrate Manufacturing", 				headquarters: "Purchase, New York")
Company.create(id: 57,  symbol: "PM",   name: "Philip Morris Int'l", 		sector: "Consumer Staples", 	  industry: "Farming/Seeds/Milling", 									headquarters: "New York, New York")
Company.create(id: 58,  symbol: "PG",   name: "Procter & Gamble", 			sector: "Consumer Staples", 	  industry: "Soap & Cleaning Compound Manufacturing", 					headquarters: "Cincinnati, Ohio")
Company.create(id: 59,  symbol: "SWY",  name: "Safeway Inc.", 				sector: "Consumer Staples", 	  industry: "Supermarkets & Other Grocery (except Convenience) Stores", headquarters: "Pleasanton, California")
Company.create(id: 60,  symbol: "SJM",  name: "Smucker (J.M.)", 			sector: "Consumer Staples", 	  industry: "Fruit & Vegetable Canning, Pickling, & Drying", 			headquarters: "Orrville, Ohio")
Company.create(id: 61,  symbol: "HSY",  name: "The Hershey Company", 		sector: "Consumer Staples", 	  industry: "Chocolate & Confectionery Manufacturing from Cacao Beans", headquarters: "Hershey, Pennsylvania")
Company.create(id: 62,  symbol: "TSN",  name: "Tyson Foods", 				sector: "Consumer Staples", 	  industry: "Meat/Poultry/Fish", 										headquarters: "Springdale, Arkansas")
Company.create(id: 63,  symbol: "WMT",  name: "Wal-Mart Stores", 			sector: "Consumer Staples", 	  industry: "Department/Specialty Retail Stores", 						headquarters: "Bentonville, Arkansas")
Company.create(id: 64,  symbol: "WAG",  name: "Walgreen Co.", 				sector: "Consumer Staples", 	  industry: "Medical/Nursing Services", 								headquarters: "Deerfield, Illinois")
Company.create(id: 65,  symbol: "WFM",  name: "Whole Foods Market", 		sector: "Consumer Staples", 	  industry: "Grocery Stores", 											headquarters: "Austin, Texas")
Company.create(id: 66,  symbol: "APC",  name: "Anadarko Petroleum Corp", 	sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "The Woodlands, Texas")
Company.create(id: 67,  symbol: "APA",  name: "Apache Corp.", 				sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Houston, Texas")
Company.create(id: 68,  symbol: "CHK",  name: "Chesapeake Energy", 			sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Oklahoma City, Oklahoma")
Company.create(id: 69,  symbol: "CVX",  name: "Chevron Corp.", 				sector: "Energy", 				  industry: "Petro Refineries", 										headquarters: "San Ramon, California")
Company.create(id: 70,  symbol: "COP",  name: "ConocoPhillips", 			sector: "Energy", 				  industry: "Petro Refineries", 										headquarters: "Houston, Texas")
Company.create(id: 71,  symbol: "DVN",  name: "Devon Energy Corp.", 		sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Oklahoma City, Oklahoma")
Company.create(id: 72,  symbol: "DO",   name: "Diamond Offshore Drilling",  sector: "Energy", 				  industry: "Oil & Gas Production", 									headquarters: "Houston, Texas")
Company.create(id: 73,  symbol: "XOM",  name: "Exxon Mobil Corp.", 			sector: "Energy", 				  industry: "Petro Refineries", 										headquarters: "Irving, Texas")
Company.create(id: 74,  symbol: "HAL",  name: "Halliburton Co.", 			sector: "Energy", 				  industry: "Other Heavy & Civil Engineering Construction", 			headquarters: "Houston, Texas")
Company.create(id: 75,  symbol: "NBL",  name: "Noble Energy Inc.", 			sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Houston, Texas")
Company.create(id: 76,  symbol: "OXY",  name: "Occidental Petroleum", 		sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Los Angeles, California")
Company.create(id: 77,  symbol: "BTU",  name: "Peabody Energy", 			sector: "Energy", 				  industry: "Coal Mining", 												headquarters: "St. Louis, Missouri")
Company.create(id: 78,  symbol: "PSX",  name: "Phillips 66", 				sector: "Energy", 				  industry: "Oil & Gas Refining & Marketing", 							headquarters: "Houston, Texas")
Company.create(id: 79,  symbol: "VLO",  name: "Valero Energy", 				sector: "Energy", 				  industry: "Integrated Oil Companies", 								headquarters: "San Antonio, Texas")
Company.create(id: 80,  symbol: "AFL",  name: "AFLAC Inc.", 				sector: "Financials", 			  industry: "Direct Life, Health, & Medical Insurance Carriers", 		headquarters: "Columbus, Georgia")
Company.create(id: 81,  symbol: "ALL",  name: "Allstate Corp.", 			sector: "Financials", 			  industry: "Direct Insurance (except Life, Health, & Medical)", 		headquarters: "Northfield Township, Illinois")
Company.create(id: 82,  symbol: "AXP",  name: "American Express Co.", 		sector: "Financials", 			  industry: "Financial Transactions Processing, Reserve, & Clearing Activities", headquarters: "New York, New York")
Company.create(id: 83,  symbol: "AXP",  name: "American Express Co.", 		sector: "Financials", 			  industry: "Financial Transactions Processing, Reserve, & ClearingActivities", headquarters: "New York, New York")
Company.create(id: 84,  symbol: "AIG",  name: "American Intl Group Inc.", 	sector: "Financials", 			  industry: "Direct Life, Health, & Medical Insurance Carriers", 		headquarters: "New York, New York")
Company.create(id: 85,  symbol: "BAC",  name: "Bank of America Corp.", 		sector: "Financials", 			  industry: "Commercial Banking", 										headquarters: "Charlotte, North Carolina")
Company.create(id: 86,  symbol: "BRK.B", name: "Berkshire Hathaway", 		sector: "Financials", 			  industry: "Reinsurance", 												headquarters: "Omaha, Nebraska")
Company.create(id: 87,  symbol: "COF",  name: "Capital One Financial", 		sector: "Financials", 			  industry: "Credit Card Issuing", 										headquarters: "Tysons Corner, Virginia")
Company.create(id: 88,  symbol: "SCHW", name: "Charles Schwab", 			sector: "Financials", 			  industry: "Securities Brokerage", 									headquarters: "San Francisco, California")
Company.create(id: 89,  symbol: "C",    name: "Citigroup Inc.", 			sector: "Financials", 			  industry: "Other Nondepository Credit Intermediation", 				headquarters: "New York, New York")
Company.create(id: 90,  symbol: "CMA",  name: "Comerica Inc.", 				sector: "Financials", 			  industry: "Commercial Banking", 										headquarters: "Dallas, Texas")
Company.create(id: 91,  symbol: "ETFC", name: "E-Trade", 					sector: "Financials", 			  industry: "Investment Brokerage", 									headquarters: "New York, New York")
Company.create(id: 92,  symbol: "GS",   name: "Goldman Sachs Group", 		sector: "Financials", 			  industry: "Investment Banking & Securities Dealing", 					headquarters: "New York, New York")
Company.create(id: 93,  symbol: "JPM",  name: "JPMorgan Chase & Co.", 		sector: "Financials", 			  industry: "Investment Banking & Securities Dealing", 					headquarters: "New York, New York")
Company.create(id: 94,  symbol: "MET",  name: "MetLife Inc.", 				sector: "Financials", 			  industry: "Direct Life, Health, & Medical Insurance Carriers", 		headquarters: "New York, New York")
Company.create(id: 95,  symbol: "MS,",   name: "Morgan Stanley", 			sector: "Financials", 			  industry: "Investment Banking & Securities Dealing", 					headquarters: "New York, New York")
Company.create(id: 96,  symbol: "PGR",  name: "Progressive Corp.", 			sector: "Financials", 			  industry: "Direct Insurance (except Life, Health, & Medical)", 		headquarters: "Mayfield Village, Ohio")
Company.create(id: 97,  symbol: "PLD",  name: "ProLogis", 					sector: "Financials", 			  industry: "Real Estate Investment Trusts", 							headquarters: "Denver, Colorado")
Company.create(id: 98,  symbol: "PRU",  name: "Prudential Financial", 		sector: "Financials", 			  industry: "Direct Life, Health, & Medical Insurance Carriers", 		headquarters: "Newark, New Jersey")
Company.create(id: 99,  symbol: "PSA",  name: "Public Storage", 			sector: "Financials", 			  industry: "Real Estate Investment Trusts", 							headquarters: "Glendale, California")
Company.create(id: 100, symbol: "TRV",  name: "The Travelers Companies Inc.", sector: "Financials", 		  industry: "Property-Casualty Insurers", 								headquarters: "New York, New York")
Company.create(id: 101, symbol: "TROW", name: "T. Rowe Price Group", 		sector: "Financials", 			  industry: "Investment Advice", 										headquarters: "Baltimore, Maryland")
Company.create(id: 102, symbol: "WFC",  name: "Wells Fargo", 				sector: "Financials", 			  industry: "Commercial Banking", 										headquarters: "San Francisco, California")
Company.create(id: 103, symbol: "WY",   name: "Weyerhaeuser Corp.", 		sector: "Materials", 			  industry: "Paper & Forest Products", 									headquarters: "Federal Way, Washington")
Company.create(id: 104, symbol: "BMY",  name: "Bristol-Myers Squibb", 		sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "New York, New York")
Company.create(id: 105, symbol: "DVA",  name: "DaVita Inc.", 				sector: "Health Care", 			  industry: "Hospital/Nursing Management", 								headquarters: "Denver, Colorado")
Company.create(id: 106, symbol: "JNJ",  name: "Johnson & Johnson", 			sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "New Brunswick, New Jersey")
Company.create(id: 107, symbol: "MRK",  name: "Merck & Co.", 				sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "Whitehouse Station, New Jersey")
Company.create(id: 108, symbol: "PFE",  name: "Pfizer Inc.", 				sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "New York, New York")
Company.create(id: 109, symbol: "UNH",  name: "United Health Group Inc.", 	sector: "Health Care", 			  industry: "Hospital And Medical Service Plans", 						headquarters: "Minnetonka, Minnesota")
Company.create(id: 110, symbol: "MMM",  name: "3M Co.", 					sector: "Industrials", 			  industry: "Paper Bag & Coated & Treated Paper Manufacturing", 		headquarters: "St Paul, Minnesota")
Company.create(id: 111, symbol: "BA",   name: "Boeing Company", 			sector: "Industrials", 			  industry: "Aerospace", 												headquarters: "Chicago, Illinois")
Company.create(id: 112, symbol: "CHRW", name: "C. H. Robinson Worldwide", 	sector: "Industrials", 			  industry: "Freight Transportation Arrangement", 						headquarters: "Eden Prairie, Minnesota")
Company.create(id: 113, symbol: "CAT",  name: "Caterpillar Inc.", 			sector: "Industrials", 			  industry: "Construction Machinery Manufacturing", 					headquarters: "Peoria, Illinois")
Company.create(id: 114, symbol: "CTAS", name: "Cintas Corp.", 				sector: "Industrials", 			  industry: "Men's & Boys' Cut & Sew Apparel Manufacturing", 			headquarters: "Mason, Ohio")
Company.create(id: 115, symbol: "DE",   name: "Deere & Co.", 				sector: "Industrials", 			  industry: "Agricultural Implement Manufacturing", 					headquarters: "Moline, Illinois")
Company.create(id: 116, symbol: "FDX",  name: "FedEx Corp.", 				sector: "Industrials", 			  industry: "Couriers", 												headquarters: "Memphis, Tennessee")
Company.create(id: 117, symbol: "GD",   name: "General Dynamics", 			sector: "Industrials", 			  industry: "Ship & Boat Building", 									headquarters: "Falls Church, Virginia")
Company.create(id: 118, symbol: "GE",   name: "General Electric", 			sector: "Industrials", 			  industry: "Consumer Electronics/Appliances", 							headquarters: "Fairfield, Connecticut")
Company.create(id: 119, symbol: "GWW",  name: "Grainger (W.W.) Inc.", 		sector: "Industrials", 			  industry: "Office Equipment/Supplies/Services", 						headquarters: "Lake Forest, Illinois")
Company.create(id: 120, symbol: "HON",  name: "Honeywell Int'l Inc.", 		sector: "Industrials", 			  industry: "Aerospace Product & Parts Manufacturing", 					headquarters: "Morristown, New Jersey")
Company.create(id: 121, symbol: "LLL",  name: "L-3 Communications", 		sector: "Industrials", 			  industry: "Radio, TV Broadcasting & Wireless Communications Equipment Manufacturing", headquarters: "New York, New York")
Company.create(id: 122, symbol: "LMT",  name: "Lockheed Martin Corp.", 		sector: "Industrials", 			  industry: "Aerospace Product & Parts Manufacturing", 					headquarters: "Bethesda, Maryland")
Company.create(id: 123, symbol: "NOC",  name: "Northrop Grumman Corp.", 	sector: "Industrials", 			  industry: "Navigational, Meas, Electromedical, & Control Instruments Manufacturing", headquarters: "West Falls Church, Virginia")
Company.create(id: 124, symbol: "PBI",  name: "Pitney-Bowes", 				sector: "Industrials", 			  industry: "Commercial & Service Industry Machinery Manufacturing", 	headquarters: "Stamford, Connecticut")
Company.create(id: 125, symbol: "RTN",  name: "Raytheon Co.", 				sector: "Industrials", 			  industry: "Navigational, Meas, Electromedical, & Control Instruments Manufacturing", headquarters: "Waltham, Massachusetts")
Company.create(id: 126, symbol: "LUV",  name: "Southwest Airlines", 		sector: "Industrials", 			  industry: "Scheduled Air Transportation", 							headquarters: "Dallas, Texas")
Company.create(id: 127, symbol: "TYC",  name: "Tyco International", 		sector: "Industrials", 			  industry: "Other Consumer Services", 									headquarters: "Princeton, New Jersey")
Company.create(id: 128, symbol: "UNP",  name: "Union Pacific", 				sector: "Industrials", 			  industry: "Road & Rail", 												headquarters: "Omaha, Nebraska")
Company.create(id: 129, symbol: "UPS",  name: "United Parcel Service", 		sector: "Industrials", 			  industry: "Air Freight & Logistics", 									headquarters: "Sandy Springs, Georgia")
Company.create(id: 130, symbol: "UTX",  name: "United Technologies", 		sector: "Industrials", 			  industry: "Aerospace & Defense", 										headquarters: "Hartford, Connecticut")
Company.create(id: 131, symbol: "WM",   name: "Waste Management Inc.", 		sector: "Industrials", 			  industry: "Commericial Servies & Supplies", 							headquarters: "Houston, Texas")
Company.create(id: 132, symbol: "ACN",  name: "Accenture", 					sector: "Technology", 			  industry: "Business Support Services", 								headquarters: "Dublin, Ireland")
Company.create(id: 133, symbol: "ADBE", name: "Adobe Systems Inc.", 		sector: "Technology", 			  industry: "Software Publishers", 										headquarters: "San Jose, California")
Company.create(id: 134, symbol: "AAPL", name: "Apple Inc.", 				sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "Cupertino, California")
Company.create(id: 135, symbol: "CSCO", name: "Cisco Systems", 				sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "San Jose, California")
Company.create(id: 136, symbol: "CTXS", name: "Citrix Systems", 			sector: "Technology", 			  industry: "Business Software & Services", 							headquarters: "Fort Lauderdale, Florida")
Company.create(id: 137, symbol: "DELL", name: "Dell Inc.", 					sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "Round Rock, Texas")
Company.create(id: 138, symbol: "EBAY", name: "eBay Inc.", 					sector: "Technology", 			  industry: "Catalog & Mail Order Houses", 								headquarters: "San Jose, California")
Company.create(id: 139, symbol: "FIS",  name: "Fidelity National Information Services", sector: "Technology", industry: "Software Publishers", 										headquarters: "Jacksonville, Florida")
Company.create(id: 140, symbol: "GOOG", name: "Google Inc.", 				sector: "Technology", 			  industry: "Internet Service Providers & Web Search Portals", 			headquarters: "Mountain View, California")
Company.create(id: 141, symbol: "HPQ",  name: "Hewlett-Packard", 			sector: "Technology", 			  industry: "Computer Manufacturing", 									headquarters: "Palo Alto, California")
Company.create(id: 142, symbol: "INTC", name: "Intel Corp.", 				sector: "Technology", 			  industry: "Semiconductor & Other Electronic Component Manufacturing", headquarters: "Santa Clara, California")
Company.create(id: 143, symbol: "IBM",  name: "Int'l Bus. Machines (IBM)", 	sector: "Technology", 			  industry: "Computer Systems Design & Related Services", 				headquarters: "Armonk, New York")
Company.create(id: 144, symbol: "INTU", name: "Intuit Inc.", 				sector: "Technology", 			  industry: "Software Publishers", 										headquarters: "Mountain View, California")
Company.create(id: 145, symbol: "JNPR", name: "Juniper Networks", 			sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "Sunnyvale, California")
Company.create(id: 146, symbol: "MA",   name: "Mastercard Inc.", 			sector: "Technology", 			  industry: "Business Services", 										headquarters: "Harrison, New York")
Company.create(id: 147, symbol: "MSFT", name: "Microsoft Corp.", 			sector: "Technology", 			  industry: "Software Publishers", 										headquarters: "Redmond, Washington")
Company.create(id: 148, symbol: "MSI",  name: "Motorola Solutions Inc.",    sector: "Technology", 			  industry: "Radio, TV, Broadcasting & Wireless Communications Equipment Manufacturing", headquarters: "Schaumburg, Illinois")
Company.create(id: 149, symbol: "NTAP", name: "NetApp", 					sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "Sunnyvale, California")
Company.create(id: 150, symbol: "ORCL", name: "Oracle Corp.", 				sector: "Technology", 			  industry: "Software Publishers", 										headquarters: "Redwood Shores, California")
Company.create(id: 151, symbol: "CRM",  name: "Salesforce.com", 			sector: "Technology", 			  industry: "Computer Software: Prepackaged Software", 					headquarters: "San Francisco, California")
Company.create(id: 152, symbol: "SNDK", name: "SanDisk Corp.", 				sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "Milpitas, California")
Company.create(id: 153, symbol: "STX",  name: "Seagate Technology", 		sector: "Technology", 			  industry: "Data Storage Devices", 									headquarters: "Dublin, Ireland")
Company.create(id: 154, symbol: "TXN",  name: "Texas Instruments", 			sector: "Technology", 			  industry: "Semiconductor & Other Electronic Component Manufacturing", headquarters: "Dallas, Texas")
Company.create(id: 155, symbol: "V",    name: "Visa Inc.",					sector: "Technology", 			  industry: "Business Services", 										headquarters: "San Francisco, California")
Company.create(id: 156, symbol: "WU",   name: "Western Union Co.", 			sector: "Technology", 			  industry: "Business Services", 										headquarters: "Englewood, Colorado")
Company.create(id: 157, symbol: "XRX",  name: "Xerox Corp.", 				sector: "Technology", 			  industry: "Office Electronics", 										headquarters: "Norwalk, Connecticut")
Company.create(id: 158, symbol: "YHOO", name: "Yahoo Inc.", 				sector: "Technology", 			  industry: "Internet Software & Services", 							headquarters: "Sunnyvale, California")
Company.create(id: 159, symbol: "AA",   name: "Alcoa Inc.", 				sector: "Materials", 			  industry: "Alumina & Aluminum Production & Processing", 				headquarters: "Pittsburgh, Pennsylvania")
Company.create(id: 160, symbol: "BLL",  name: "Ball Corp.", 				sector: "Materials", 			  industry: "Metal Can, Box, & Other Metal Container Manufacturing", 	headquarters: "Broomfield, Colorado")
Company.create(id: 161, symbol: "DOW",  name: "Dow Chemical", 				sector: "Materials", 			  industry: "Resin & Synthetic Rubber Manufacturing", 					headquarters: "Midland, Michigan")
Company.create(id: 162, symbol: "DD",   name: "Du Pont (E.I.)", 			sector: "Materials", 			  industry: "Electric Power Generation", 								headquarters: "Richmond, Virginia")
Company.create(id: 163, symbol: "ECL",  name: "Ecolab Inc.", 				sector: "Materials", 			  industry: "Soap & Cleaning Compound Manufacturing", 					headquarters: "St. Paul, Minnesota")
Company.create(id: 164, symbol: "MON",  name: "Monsanto Co.", 				sector: "Materials", 			  industry: "Pesticide & Other Agricultural Chemical Manufacturing", 	headquarters: "Creve Coeur, Missouri")
Company.create(id: 165, symbol: "NEM",  name: "Newmont Mining Corp.", 		sector: "Materials", 			  industry: "Gold Ore & Silver Ore Mining", 							headquarters: "Denver, Colorado")
Company.create(id: 166, symbol: "NUE",  name: "Nucor Corp.", 				sector: "Materials", 			  industry: "Iron & Steel Mills & Ferroalloy Manufacturing", 			headquarters: "Charlotte, North Carolina")
Company.create(id: 167, symbol: "X",    name: "United States Steel Corp.",  sector: "Materials", 			  industry: "Metals & Mining", 											headquarters: "Pittsburgh, Pennsylvania")
Company.create(id: 168, symbol: "T",    name: "AT&T Inc.", 					sector: "Technology", 			  industry: "Wired Telecommunications Carriers", 						headquarters: "Dallas, Texas")
Company.create(id: 169, symbol: "CTL",  name: "CenturyLink Inc.", 			sector: "Technology", 			  industry: "Wired Telecommunications Carriers", 						headquarters: "Monroe, Louisiana")
Company.create(id: 170, symbol: "S",    name: "Sprint Nextel Corp.", 		sector: "Technology", 			  industry: "Wired Telecommunications Carriers", 						headquarters: "Overland Park, Kansas")
Company.create(id: 171, symbol: "VZ",   name: "Verizon Communications", 	sector: "Technology", 			  industry: "Diversified Telecommunication Services", 					headquarters: "New York, New York")
Company.create(id: 172, symbol: "ED",   name: "Consolidated Edison", 		sector: "Utilities", 			  industry: "Power Generation", 										headquarters: "New York, New York")
Company.create(id: 173, symbol: "DUK",  name: "Duke Energy", 				sector: "Utilities", 			  industry: "Power Generation", 										headquarters: "Charlotte, North Carolina")
Company.create(id: 174, symbol: "XEL",  name: "Xcel Energy Inc.", 			sector: "Utilities",			  industry: "Multi-Utilities", 											headquarters: "Minneapolis, Minnesota")
Company.create(id: 175, symbol: "AEP",  name: "American Electric Power Co", sector: "Utilities", 			  industry: "Electric Utilities: Central", 								headquarters: "Columbus, Ohio")
Company.create(id: 176, symbol: "SO",   name: "Southern Co.", 				sector: "Utilities", 			  industry: "Electric Utilities: Central", 								headquarters: "Atlanta, Georgia")
Company.create(id: 177, symbol: "NEE",  name: "NextEra Energy Inc.", 		sector: "Utilities", 			  industry: "Electric Utilities: Central", 								headquarters: "Juno Beach, Florida")
Company.create(id: 178, symbol: "D",    name: "Dominion Resources", 		sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Richmond, Virginia")
Company.create(id: 179, symbol: "EXC",  name: "Exelon Corp.", 				sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Chicago, Illinois")
Company.create(id: 180, symbol: "SRE",  name: "Sempra Energy", 				sector: "Utilities", 			  industry: "Natural Gas Distribution",    								headquarters: "San Diego, California")
Company.create(id: 181, symbol: "PPL",  name: "PPL Corp.", 					sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Allentown, Pennsylvania")
Company.create(id: 182, symbol: "PCG",  name: "PG &E Corp.", 				sector: "Utilities", 			  industry: "Gas & Electric ",             								headquarters: "San Francisco, California")
Company.create(id: 183, symbol: "PEG",  name: "Public Service Enterprise Group", sector: "Utilities", 		  industry: "Electric Power Generation",   								headquarters: "Newark, New Jersey")
Company.create(id: 184, symbol: "FE",   name: "FirstEnergy Corp.", 			sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Akron, Ohio")
Company.create(id: 185, symbol: "EIX",  name: "Edison International", 		sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Rosemead, California")
Company.create(id: 186, symbol: "NU",   name: "Northeast Utilities Systems",sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Berlin, Connecticut")
Company.create(id: 187, symbol: "EQT",  name: "EQT Corp.", 					sector: "Utilities", 			  industry: "Exploration & Production",    								headquarters: "Pittsburgh, Pennsylvania")
Company.create(id: 188, symbol: "DTE",  name: "DTE Energy ", 				sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "Detroit, Michigan")
Company.create(id: 189, symbol: "ETR",  name: "Entergy Corp.", 				sector: "Utilities", 			  industry: "Electric Power Generation",   								headquarters: "New Orleans, Louisiana")
Company.create(id: 190, symbol: "PX",   name: "Praxair Inc.", 				sector: "Materials", 			  industry:	"Industrial Gas Manufacturing", 							headquarters: "Danbury, Connecticut")
Company.create(id: 191, symbol: "FCX",  name: "Freeport-McMoran Copper & Gold", sector: "Materials",		  industry: "Copper, Nickel, Lead, & Zinc Mining", 						headquarters: "Phoenix, Arizona")
Company.create(id: 192, symbol: "SCCO", name: "Southern Copper Corp.", 		sector: "Materials", 			  industry:	"Precious Metals", 											headquarters: "Phoenix, Arizona")
Company.create(id: 193, symbol: "PPG",  name: "PPG Industries Inc.", 		sector: "Materials", 			  industry:	"Paint & Coating Manufacturing", 							headquarters: "Pittsburgh, Pennsylvania")
Company.create(id: 194, symbol: "WPZ",  name: "Williams Partners L.P.", 	sector: "Materials", 			  industry:	"Natural Gas Distribution", 								headquarters: "Tulsa, Oklahoma")
Company.create(id: 195, symbol: "APD",  name: "Air Products and Chemicals", sector: "Materials", 			  industry:	"Industrial Gas Manufacturing", 							headquarters: "Allentown, Pennsylvania")
Company.create(id: 196, symbol: "MOS",  name: "Mosaic", 					sector: "Materials", 			  industry:	"Agricultural Chemicals", 									headquarters: "Plymouth, Minnesota")
Company.create(id: 197, symbol: "EMN",  name: "Eastman Chemical Co.", 		sector: "Materials", 			  industry:	"Resin & Synthetic Rubber Manufacturing", 					headquarters: "Kingsport, Tennessee")
Company.create(id: 198, symbol: "CF",   name: "CF Industries Holdings Inc.",sector: "Materials", 			  industry:	"Agricultural Chemicals", 									headquarters: "Deerfield, Illinois")
Company.create(id: 199, symbol: "SIAL", name: "Sigma - Aldrich Corp.", 		sector: "Materials", 			  industry:	"Pharmaceutical & Medicine Manufacturing", 					headquarters: "St. Louis, Missouri")
Company.create(id: 200, symbol: "FMC",  name: "FMC Corp.", 					sector: "Materials", 			  industry:	"Major Chemicals", 											headquarters: "Philadelphia, Pennsylvania")
Company.create(id: 201, symbol: "CE",   name: "Celanese Corp.", 			sector: "Materials", 			  industry:	"Major Chemicals", 											headquarters: "Irving, Texas")
Company.create(id: 202, symbol: "ARG",  name: "Airgas Inc.", 				sector: "Materials", 			  industry:	"Industrial Machinery & Equipment Merchant Wholesalers",    headquarters: "Radnor Township, Pennsylvania")
Company.create(id: 204, symbol: "MO",   name: "Altria Group. Inc.", 		sector: "Consumer Discretionary", industry: "Tobacco Product Manufacturing", 							headquarters: "Richmond, Virginia")
Company.create(id: 205, symbol: "GM",   name: "General Motors", 			sector: "Consumer Discretionary", industry: "Auto Manufacturing", 										headquarters: "Detroit, Michigan")
Company.create(id: 206, symbol: "JCI",  name: "Johnson Controls Inc.", 		sector: "Consumer Discretionary", industry: "Motor Vehicle Seating & Interior Trim Manufacturing", 		headquarters: "Milwaukee, Wisconsin")
Company.create(id: 207, symbol: "RAI",  name: "Reynolds American Inc.", 	sector: "Consumer Discretionary", industry: "Tobacco Product Manufacturing", 							headquarters: "Winston-Salem, North Carolina")
Company.create(id: 208, symbol: "EL",   name: "Estee Lauder Companies Inc.",sector: "Consumer Discretionary", industry: "Toilet Preparation Manufacturing", 						headquarters: "New York, New York")
Company.create(id: 209, symbol: "ADM",  name: "Archer Daniels Midland Co.", sector: "Consumer Discretionary", industry: "Starch & Vegetable Fats & Oils Manufacturing", 			headquarters: "Decatur, Illinois")
Company.create(id: 210, symbol: "IP",   name: "International Paper Co.", 	sector: "Consumer Discretionary", industry: "Paper Bag & Coated & Treated Paper Manufacturing", 		headquarters: "Memphis, Tennessee")
Company.create(id: 211, symbol: "FOXA", name: "Twenty-First Century Fox", 	sector: "Consumer Discretionary", industry: "Entertainment - Diversified", 								headquarters: "New York, New York")
Company.create(id: 212, symbol: "LVS",  name: "Las Vegas Sands Corp.", 		sector: "Consumer Discretionary", industry: "Hotels/Resorts", 											headquarters: "Las Vegas, Nevada")
Company.create(id: 213, symbol: "TJX",  name: "TJX Companies Inc.", 		sector: "Consumer Discretionary", industry: "Specialty Retail", 										headquarters: "Framingham, Massachusetts")
Company.create(id: 214, symbol: "GILD", name: "Gilead Sciences Inc.", 		sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "Foster City, California")
Company.create(id: 215, symbol: "AMGN", name: "Amgen Inc.", 				sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "Thousand Oaks, California")
Company.create(id: 216, symbol: "ABBV", name: "Abbvie Inc.", 				sector: "Health Care", 			  industry: "Biotechnology", 											headquarters: "North Chicago, Illinois")
Company.create(id: 217, symbol: "LLY",  name: "Eli Lilly and Company", 		sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "Indianapolis, Indiana")
Company.create(id: 218, symbol: "CELG", name: "Celgene Corp.", 				sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "Summit, New Jersey")
Company.create(id: 219, symbol: "ABT",  name: "Abbott Laboratories", 		sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "North Chicago, Illinois")
Company.create(id: 221, symbol: "ESRX", name: "Express Scripts Holding Co", sector: "Health Care", 			  industry: "Other Insurance Related Activities", 						headquarters: "Cool Valley, Missouri")
Company.create(id: 222, symbol: "MDT",  name: "Medtronic Inc.", 			sector: "Health Care", 			  industry: "Navigational, Meas, Electromedical, & Control Instruments Manufacturing", headquarters: "Fridley, Minnesota")
Company.create(id: 223, symbol: "BIIB", name: "Biogen Idec Inc.", 			sector: "Health Care", 			  industry: "Biotechnology", 											headquarters: "Weston, Massachusetts")
Company.create(id: 224, symbol: "BAX",  name: "Baxter International Inc.",  sector: "Health Care", 			  industry: "Medical Equipment & Supplies Manufacturing", 				headquarters: "Deerfield, Illinois")
Company.create(id: 225, symbol: "TMO ", name: "Thermo Fisher Scientific",   sector: "Health Care", 			  industry: "Navigational, Meas, Electromedical, & Control Instruments Manufacturing", headquarters: "Waltham, Massachusetts")
Company.create(id: 226, symbol: "AGN",  name: "Allergan Inc.", 				sector: "Health Care", 			  industry: "Pharmaceutical & Medicine Manufacturing", 					headquarters: "Irvine, California")
Company.create(id: 227, symbol: "WLP",  name: "Wellpoint Inc.", 			sector: "Health Care", 			  industry: "Hospital And Medical Service Plans", 						headquarters: "Indianapolis, Indiana")
Company.create(id: 228, symbol: "SYK",  name: "Stryker Corp.", 				sector: "Health Care", 			  industry: "Medical Equipment & Supplies Manufacturing", 				headquarters: "Kalamazoo, Michigan")
Company.create(id: 229, symbol: "REGN", name: "Regeneron Pharmaceuticals",  sector: "Health Care", 			  industry: "Biotechnology", 											headquarters: "Tarrytown, New York")
Company.create(id: 230, symbol: "SLB",  name: "Schlumberger Limited ", 		sector: "Energy", 				  industry: "Oil & Gas Pipeline & Related Structures Construction", 	headquarters: "Houston, Texas")
Company.create(id: 231, symbol: "EPD",  name: "Enterprise Products Partners",sector: "Energy", 				  industry: "Oil & Gas Distribution", 									headquarters: "Houston, Texas")
Company.create(id: 232, symbol: "EOG",  name: "EOG Resources Inc.", 		sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Houston, Texas")
Company.create(id: 233, symbol: "KMI",  name: "Kinder Morgan Inc.", 		sector: "Energy", 				  industry: "Pipeline Transportation of Natural Gas", 					headquarters: "Houston, Texas")
Company.create(id: 234, symbol: "KMP",  name: "Kinder Morgan Energy Partners",sector: "Energy", 			  industry: "Pipeline Transportation of Natural Gas", 					headquarters: "Houston, Texas")
Company.create(id: 235, symbol: "NOV",  name: "National Oilwell Varco Inc.",sector: "Energy", 				  industry: "Mining & Oil & Gas Field Machinery Manufacturing", 		headquarters: "Houston, Texas")
Company.create(id: 236, symbol: "HES",  name: "Hess Corp", 					sector: "Energy", 				  industry: "Petro Refineries", 										headquarters: "New York, New York")
Company.create(id: 237, symbol: "WMB",  name: "Williams Companies", 		sector: "Energy", 				  industry: "Natural Gas Distribution", 								headquarters: "Tulsa, Oklahoma")
Company.create(id: 238, symbol: "PXD",  name: "Pioneer Natural Resources",  sector: "Energy", 				  industry: "Oil & Gas Extraction", 									headquarters: "Irving, Texas")
Company.create(id: 239, symbol: "MRO",  name: "Marathon Oil Corp.", 		sector: "Energy", 				  industry: "Petro Refineries", 										headquarters: "Houston, Texas")
Company.create(id: 240, symbol: "MPC",  name: "Marathon Petroleum Corp.", 	sector: "Energy", 				  industry: "Oil & Gas Exploration/Production", 						headquarters: "Findlay, Ohio")
Company.create(id: 241, symbol: "QCOM", name: "QUALCOMM Inc.", 				sector: "Technology", 			  industry: "Radio, TV Broadcasting & Wireless Communications Equipment Manufacturing", headquarters: "San Diego, California")
Company.create(id: 242, symbol: "FB",   name: "Facebook", 					sector: "Technology", 			  industry: "Internet", 												headquarters: "Menlo Park, California")
Company.create(id: 243, symbol: "EMC",  name: "EMC Corporation", 			sector: "Technology", 			  industry: "Computer & Peripheral Equipment Manufacturing", 			headquarters: "Hopkinton, Massachusetts")
Company.create(id: 244, symbol: "EMR",  name: "Emerson Electric Co.", 		sector: "Technology", 			  industry: "Consumer Electronics/Appliances", 							headquarters: "Ferguson, Missouri")
Company.create(id: 245, symbol: "VMW",  name: "VMWare Inc.", 				sector: "Technology", 			  industry: "Computer Software: Prepackaged Software", 					headquarters: "Palo Alto, California")
Company.create(id: 246, symbol: "ADP",  name: "Automatic Data Processing",  sector: "Technology", 			  industry: "Data Processing, Hosting, & Related Services", 			headquarters: "Roseland, New Jersey")
Company.create(id: 247, symbol: "ETN",  name: "Eaton Corp.", 				sector: "Technology", 			  industry: "Motor Vehicle Gasoline Engine & Engine Parts Manufacturing",headquarters: "Cleveland, Ohio")
Company.create(id: 248, symbol: "LNKD", name: "LinkedIn Corp.", 			sector: "Technology", 			  industry: "Business Training & Employment Agencies", 					headquarters: "Mountain View, California")
Company.create(id: 249, symbol: "PCLN", name: "Priceline.com", 				sector: "Technology", 			  industry: "Business Services", 										headquarters: "Norwalk, Connecticut")
Company.create(id: 250, symbol: "USB",  name: "US Bancorp", 				sector: "Financials", 			  industry: "Banks", 													headquarters: "Minneapolis, Minnesota")
Company.create(id: 251, symbol: "SPG",  name: "Simon Property Group, Inc.", sector: "Financials", 			  industry: "Real Estate Investment Trusts", 							headquarters: "Indianapolis, Indiana")
Company.create(id: 252, symbol: "BLK",  name: "BlackRock Inc.", 			sector: "Financials", 			  industry: "Investment Bankers/Brokers/Service", 						headquarters: "New York, New York")
Company.create(id: 253, symbol: "PNC",  name: "PNC Financial Services Group",sector: "Financials", 			  industry: "Commercial Banking", 										headquarters: "Pittsburgh, Pennsylvania")
Company.create(id: 254, symbol: "BK",   name: "The Bank of New York Mellon",sector: "Financials", 			  industry: "Commercial Banking", 										headquarters: "New York, New York")
Company.create(id: 255, symbol: "STT",  name: "State Street Corp.", 		sector: "Financials", 			  industry: "Commercial Banking", 										headquarters: "Boston, Massachusetts")
Company.create(id: 256, symbol: "DHR",  name: "Danaher Corp.", 				sector: "Industrials", 			  industry: "Navigational, Meas, Electromedical, & Control Instruments Manufacturing", headquarters: "Washington D.C")
Company.create(id: 257, symbol: "ITW",  name: "Illinois Tool Works Inc.",   sector: "Industrials", 			  industry: "All Other General Purpose Machinery Manufacturing", 		headquarters: "Glenview, Illinois")
Company.create(id: 258, symbol: "PCP",  name: "Precision Castparts Corp.",  sector: "Industrials", 			  industry: "Ferrous Metal Foundries", 									headquarters: "Portland, Oregon")
Company.create(id: 259, symbol: "CMI",  name: "Cummins Inc.", 				sector: "Industrials", 			  industry: "Engine, Turbine, & Power Transmission Equipment Manufacturing", headquarters: "Columbus, Indiana")
Company.create(id: 260, symbol: "PH",   name: "Parker Hannifin Corp.", 		sector: "Industrials", 			  industry: "Metal Valve Manufacturing", 								headquarters: "Cleveland, Ohio")
Company.create(id: 261, symbol: "DOV",  name: "Dover Corp.", 				sector: "Industrials", 			  industry: "Other Industrial Machinery Manufacturing", 				headquarters: "Downers Grove, Illinois")
Company.create(id: 262, symbol: "SWK",  name: "Stanley Black & Decker", 	sector: "Industrials", 			  industry: "Cutlery & Handtool Manufacturing", 						headquarters: "New Britain, Connecticut")
Company.create(id: 263, symbol: "MDLZ", name: "Mondelez International Inc.",sector: "Consumer Staples",		  industry: "Food Products", 											headquarters: "Deerfield, Illinois")
